---
Name: user_defined_exports
After:
  - 'framework/*'
  - 'cms/*'
---
SilverStripe\Admin\ModelAdmin:
  extensions:
    - UserDefinedExports\Extensions\UserDefinedExportsModelAdminExtension
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - UserDefinedExports\Extensions\UserDefinedExportsSiteConfigExtension