---
Name: user_defined_exports
After:
  - 'framework/*'
---
SilverStripe\Admin\ModelAdmin:
  extensions:
    - UserDefinedExports\Extensions\UserDefinedExportsModelAdminExtension
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - UserDefinedExports\Extensions\UserDefinedExportsSiteConfigExtension

SilverStripe\Admin\LeftandMain:
  admin_themes:
    - 'user-defined-exports-admin'