---
Name: user_defined_exports
After:
  - 'framework/*'
  - 'cms/*'
---
ModelAdmin:
  extensions:
    - UserDefinedExportsModelAdminExtension
SiteConfig:
  extensions:
    - UserDefinedExportsSiteConfigExtension